#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$DATABASE_NAME" <<-EOSQL
    CREATE SCHEMA IF NOT EXISTS $SCHEMA_NAME;
    GRANT ALL PRIVILEGES ON SCHEMA $SCHEMA_NAME TO $DATABASE_USER;
    ALTER USER $DATABASE_USER SET search_path TO $SCHEMA_NAME;
    CREATE EXTENSION IF NOT EXISTS "uuid-ossp" SCHEMA $SCHEMA_NAME;
EOSQL
