// Package port provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.13.4 DO NOT EDIT.
package port

import (
	openapi_types "github.com/deepmap/oapi-codegen/pkg/types"
)

// Error error message
type Error struct {
	// Code http error code
	Code int `json:"code"`

	// Message i18n description
	Message string `json:"message"`
}

// User defines model for User.
type User struct {
	Email *openapi_types.Email `json:"email,omitempty"`
	Name  *string              `json:"name,omitempty"`
	Uuid  *string              `json:"uuid,omitempty"`
}

// UserInput defines model for UserInput.
type UserInput struct {
	Email openapi_types.Email `json:"email"`
	Name  string              `json:"name"`
}

// PostUsersJSONRequestBody defines body for PostUsers for application/json ContentType.
type PostUsersJSONRequestBody = UserInput

// PutUsersUuidJSONRequestBody defines body for PutUsersUuid for application/json ContentType.
type PutUsersUuidJSONRequestBody = UserInput
